# Configuracion de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-db-m3
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA y Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar cache de Thymeleaf para desarrollo
spring.thymeleaf.cache=false

server.port=8081

